### ISSUE TITLE
[Feature Request] Ability to send titles along with messages

### ISSUE THREAD

**Issue by Folas1337** [teunjojo/SimpleAutoRestart#6]
I am currently using UltimateAutoRestart but want to switch but I like how you can send titles on UAR so the only thing preventing me from switching to this is the titles.

Ideally we can simply set up the config.yml like this:
```yaml
# The hour and minute when the server should restart (24 hour format)
restartTime:
- '00:00'
# Add multiple times by adding a new line like: - '12:00'

messages: []
#Since I don't want to use messages, I'd leave them empty, hope this actually works.

titles:
  5min: "Restarting in 5 minutes"
  now: "Restarting now"

subtitles:
  5min: "We'll be right back"
  now: "We'll be right back"
```

Something like that would definitely be appreciated on my end 😄
